// SPDX-License-Identifier: AGPL-3.0-or-later

package e2e

import (
	"strings"
	"testing"
	"time"
)

// TestChat_AutoTitleNeverOverwritesAUserRename was found live: a chat's
// title is generated by a separate LLM call after its first reply, and
// renaming the chat while that call was still in flight got the user's name
// silently replaced by the generated one a moment later.
func TestChat_AutoTitleNeverOverwritesAUserRename(t *testing.T) {
	h := NewHarness(t)
	h.SetWebSearchEnabled(false)
	titleAsked := make(chan struct{}, 1)
	release := make(chan struct{})
	h.Fake.Script = func(callNum int, req FakeChatRequest) FakeChatResponse {
		if strings.Contains(string(req.Raw), "generate a very short chat title") {
			titleAsked <- struct{}{}
			<-release // hold the title call open while the user renames
			return FakeChatResponse{Text: "Generated Title"}
		}
		return FakeChatResponse{Text: "hello"}
	}
	chatID := h.NewChat()
	h.SendMessageStream(chatID, "first message")

	select {
	case <-titleAsked:
	case <-time.After(5 * time.Second):
		t.Fatal("the automatic title request never arrived")
	}
	h.postJSON("/api/chats/rename", map[string]string{"id": chatID, "title": "My Own Name"}).Body.Close()
	close(release)

	deadline := time.Now().Add(3 * time.Second)
	var title string
	for time.Now().Before(deadline) {
		var chats []struct {
			ID    string `json:"id"`
			Title string `json:"title"`
		}
		decodeInto(t, h.getJSON("/api/chats"), &chats)
		for _, c := range chats {
			if c.ID == chatID {
				title = c.Title
			}
		}
		if title == "Generated Title" {
			break
		}
		time.Sleep(50 * time.Millisecond)
	}
	if title != "My Own Name" {
		t.Errorf("chat title = %q, want the user's rename to survive the in-flight auto-title", title)
	}
}
