import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/l10n.dart';
import '../../../core/theme.dart';
import '../../../providers/chat_provider.dart';
import '../../../core/friendly_error.dart';

/// Dedicated settings page for importing a personal-context profile
/// generated by another AI assistant (ChatGPT, Gemini, Claude, etc.) into
/// Memo's own memory + learned communication style. Deliberately does not
/// include a "import conversation history" flow (unlike Gemini's own
/// settings page this is visually modeled after) — only the prompt-based
/// memory transfer.
class MemoryImportTab extends ConsumerStatefulWidget {
  const MemoryImportTab({super.key});

  @override
  ConsumerState<MemoryImportTab> createState() => _MemoryImportTabState();
}

class _MemoryImportTabState extends ConsumerState<MemoryImportTab> {
  final _importController = TextEditingController();
  bool _importing = false;
  // Result feedback is shown inline (not via ScaffoldMessenger/SnackBar):
  // this whole page lives inside SettingsDialog's modal Dialog, which sits
  // above the app's root Scaffold in the overlay stack — a SnackBar shown
  // from here renders behind the still-open dialog and is invisible to the
  // user until they close Settings, which looked exactly like "nothing
  // happened" when reported.
  String? _statusMessage;
  bool _statusIsError = false;

  @override
  void dispose() {
    _importController.dispose();
    super.dispose();
  }

  // Always English, regardless of the app's own locale — the destination
  // (this app's own structuring LLM, internal/app/memory_import.go) parses
  // English most reliably, and the target AI (ChatGPT/Gemini/Claude/etc.)
  // handles an English instruction prompt just as well as a localized one.
  static const String _memoryImportPrompt =
      'You are helping migrate a user\'s context from one AI assistant to another. Your task is to review your entire conversation history with the user — not just the most recent messages — and summarize everything you know about them, drawing on every relevant signal, not only messages with an exact quotable line.\n\n'
      'In the output, do not use first-person pronouns (I, me, my, we, us, our) or second-person pronouns (you, your, yours). Instead, refer to the person being summarized as "the user", or use neutral phrasing.\n\n'
      'Quote the user\'s own words verbatim wherever a direct quote is available, especially for instructions and preferences. When no single quotable line captures an observation — for example, a pattern noticed across several messages — describe it in your own words instead of skipping it. Never let the absence of an exact quote cause you to drop a real signal.\n\n'
      'Categories (present in this order):\n'
      '1. Demographics: Preferred name(s), occupation, education, and general place of residence.\n'
      '2. Interests & Preferences: Sustained, ongoing engagement — not a one-off purchase or a single mention of owning something.\n'
      '3. Relationships: Confirmed, ongoing relationships.\n'
      '4. Dated Events, Projects & Plans: A log of significant and recent events.\n'
      '5. Communication Style & Personality: Patterns in tone, formality, directness, humor, and emotional register — how the user prefers to be talked to. This category is inherently a synthesis across the whole conversation, not a single message — do not skip it just because no single message states it explicitly.\n'
      '6. Instructions: Rules the user has explicitly asked to be followed going forward ("always do X", "never do Y") and corrections about your behavior. Only include rules that came from an explicit request, not incidental phrasing from casual conversation.\n\n'
      'Format:\n'
      'Break the content into labeled sections using the categories above. Structure each entry like this:\n\n'
      '* The user\'s name is <name>.\n'
      '    - Evidence: The user said, "Call me <name>." Date: [YYYY-MM-DD].\n\n'
      'If no direct quote is available for an entry, replace the "Evidence:" line with "Basis: <brief description of the pattern observed>" instead of omitting the entry.\n\n'
      'Output:\n'
      '- Be as thorough as possible — the goal is a complete profile, not a minimal one.\n'
      '- Output ONLY the requested information. Do not add filler, an introduction, or a closing remark.\n'
      '- Only omit a category if there is truly nothing relevant anywhere in the conversation history.\n\n'
      'Finally, end with the exact line "Source: <name>" (replace <name> with this assistant\'s name — e.g. ChatGPT, Gemini, Claude, Grok). This must be the very last line of the response.';

  Future<void> _submitMemoryImport() async {
    final text = _importController.text.trim();
    if (text.isEmpty) {
      setState(() {
        _statusMessage = L10n.t('memory_import_empty_error');
        _statusIsError = true;
      });
      return;
    }
    setState(() {
      _importing = true;
      _statusMessage = null;
    });
    try {
      final result = await ref.read(apiClientProvider).importMemoryFromText(text);
      final factsSaved = result['factsSaved'] as int;
      final styleUpdated = result['styleUpdated'] as bool;
      if (mounted) {
        final message = factsSaved == 0
            ? L10n.t('memory_import_no_facts')
            : L10n.t('memory_import_success_facts', {'count': '$factsSaved'}) +
                (styleUpdated ? L10n.t('memory_import_success_style') : '');
        setState(() {
          _statusMessage = message;
          _statusIsError = factsSaved == 0;
        });
        if (factsSaved > 0) {
          _importController.clear();
        }
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _statusMessage = '${L10n.t('error')}: ${FriendlyError.describeGeneric(e)}';
          _statusIsError = true;
        });
      }
    } finally {
      if (mounted) setState(() => _importing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = MemoTheme.of(context);
    return ListView(
      padding: EdgeInsets.all(32),
      children: [
        Text(
          L10n.t('memory_import_title'),
          style: Theme.of(context).textTheme.titleLarge?.copyWith(
            fontWeight: FontWeight.bold,
            color: theme.textMain,
          ),
        ),
        SizedBox(height: 8),
        Text(
          L10n.t('memory_import_hint'),
          style: TextStyle(color: theme.textDim, fontSize: 13),
        ),
        SizedBox(height: 24),

        _StepHeader(number: 1, label: L10n.t('memory_import_step1')),
        SizedBox(height: 12),
        Container(
          padding: EdgeInsets.all(16),
          decoration: BoxDecoration(
            color: theme.bgPanel,
            borderRadius: BorderRadius.circular(MemoTheme.radiusMd),
            border: Border.all(color: theme.borderSoft),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              ConstrainedBox(
                constraints: BoxConstraints(maxHeight: 160),
                child: SingleChildScrollView(
                  child: Text(
                    _memoryImportPrompt,
                    style: TextStyle(fontSize: 13, color: theme.textSecondary, height: 1.4),
                  ),
                ),
              ),
              SizedBox(height: 14),
              Align(
                alignment: Alignment.centerRight,
                child: OutlinedButton.icon(
                  icon: Icon(Icons.copy, size: 16),
                  label: Text(L10n.t('memory_import_copy_prompt')),
                  style: OutlinedButton.styleFrom(
                    shape: StadiumBorder(),
                    side: BorderSide(color: theme.borderSoft),
                  ),
                  onPressed: () {
                    Clipboard.setData(ClipboardData(text: _memoryImportPrompt));
                    setState(() {
                      _statusMessage = L10n.t('memory_import_prompt_copied');
                      _statusIsError = false;
                    });
                  },
                ),
              ),
            ],
          ),
        ),
        SizedBox(height: 16),
        _TipBanner(text: L10n.t('memory_import_tip')),
        SizedBox(height: 28),

        _StepHeader(number: 2, label: L10n.t('memory_import_step2')),
        SizedBox(height: 12),
        Container(
          padding: EdgeInsets.all(16),
          decoration: BoxDecoration(
            color: theme.bgPanel,
            borderRadius: BorderRadius.circular(MemoTheme.radiusMd),
            border: Border.all(color: theme.borderSoft),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              TextField(
                controller: _importController,
                maxLines: 10,
                minLines: 6,
                style: TextStyle(fontSize: 13),
                decoration: InputDecoration(
                  hintText: L10n.t('memory_import_placeholder'),
                  filled: true,
                  fillColor: theme.bgApp,
                  contentPadding: EdgeInsets.all(12),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(MemoTheme.radiusSm),
                    borderSide: BorderSide(color: theme.borderSoft),
                  ),
                  enabledBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(MemoTheme.radiusSm),
                    borderSide: BorderSide(color: theme.borderSoft),
                  ),
                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(MemoTheme.radiusSm),
                    borderSide: BorderSide(color: MemoTheme.accent),
                  ),
                ),
              ),
              SizedBox(height: 14),
              Align(
                alignment: Alignment.centerRight,
                child: ElevatedButton.icon(
                  onPressed: _importing ? null : _submitMemoryImport,
                  style: ElevatedButton.styleFrom(shape: StadiumBorder()),
                  icon: _importing
                      ? SizedBox(
                          width: 14,
                          height: 14,
                          child: CircularProgressIndicator(strokeWidth: 2),
                        )
                      : Icon(Icons.add, size: 18),
                  label: Text(L10n.t('memory_import_submit')),
                ),
              ),
            ],
          ),
        ),
        if (_statusMessage != null) ...[
          SizedBox(height: 16),
          _StatusBanner(text: _statusMessage!, isError: _statusIsError),
        ],
      ],
    );
  }
}

class _StepHeader extends StatelessWidget {
  final int number;
  final String label;

  const _StepHeader({required this.number, required this.label});

  @override
  Widget build(BuildContext context) {
    final theme = MemoTheme.of(context);
    return Row(
      children: [
        Container(
          width: 22,
          height: 22,
          alignment: Alignment.center,
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            border: Border.all(color: theme.borderSoft),
          ),
          child: Text(
            '$number',
            style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: theme.textDim),
          ),
        ),
        SizedBox(width: 10),
        Expanded(
          child: Text(
            label,
            style: TextStyle(fontSize: 13, fontWeight: FontWeight.w500, color: theme.textSecondary),
          ),
        ),
      ],
    );
  }
}

class _StatusBanner extends StatelessWidget {
  final String text;
  final bool isError;

  const _StatusBanner({required this.text, required this.isError});

  @override
  Widget build(BuildContext context) {
    final theme = MemoTheme.of(context);
    final color = isError ? MemoTheme.red : MemoTheme.green;
    return Container(
      padding: EdgeInsets.symmetric(horizontal: 12, vertical: 10),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.10),
        borderRadius: BorderRadius.circular(MemoTheme.radiusSm),
        border: Border.all(color: color.withValues(alpha: 0.35)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(
            isError ? Icons.error_outline : Icons.check_circle_outline,
            size: 16,
            color: color,
          ),
          SizedBox(width: 10),
          Expanded(
            child: Text(
              text,
              style: TextStyle(fontSize: 12.5, color: theme.textSecondary, height: 1.4),
            ),
          ),
        ],
      ),
    );
  }
}

class _TipBanner extends StatelessWidget {
  final String text;

  const _TipBanner({required this.text});

  @override
  Widget build(BuildContext context) {
    final theme = MemoTheme.of(context);
    return Container(
      padding: EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: MemoTheme.warningOrange.withValues(alpha: 0.10),
        borderRadius: BorderRadius.circular(MemoTheme.radiusSm),
        border: Border.all(color: MemoTheme.warningOrange.withValues(alpha: 0.35)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(Icons.lightbulb_outline, size: 16, color: MemoTheme.warningOrange),
          SizedBox(width: 10),
          Expanded(
            child: Text(
              text,
              style: TextStyle(fontSize: 12.5, color: theme.textSecondary, height: 1.4),
            ),
          ),
        ],
      ),
    );
  }
}
