// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function CheckEmbeddingHealth() {
  return window['go']['main']['App']['CheckEmbeddingHealth']();
}

export function CheckLlamaInstallation() {
  return window['go']['main']['App']['CheckLlamaInstallation']();
}

export function ClearAllMemory() {
  return window['go']['main']['App']['ClearAllMemory']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DebugMemorySearch(arg1) {
  return window['go']['main']['App']['DebugMemorySearch'](arg1);
}

export function DeleteChat(arg1) {
  return window['go']['main']['App']['DeleteChat'](arg1);
}

export function DeleteLocalModel(arg1) {
  return window['go']['main']['App']['DeleteLocalModel'](arg1);
}

export function DeleteMemoryFile(arg1) {
  return window['go']['main']['App']['DeleteMemoryFile'](arg1);
}

export function DetectGPU() {
  return window['go']['main']['App']['DetectGPU']();
}

export function DownloadModel(arg1, arg2) {
  return window['go']['main']['App']['DownloadModel'](arg1, arg2);
}

export function GetActiveChatID() {
  return window['go']['main']['App']['GetActiveChatID']();
}

export function GetActiveMessages() {
  return window['go']['main']['App']['GetActiveMessages']();
}

export function GetAvailableStyles() {
  return window['go']['main']['App']['GetAvailableStyles']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloadProgress() {
  return window['go']['main']['App']['GetDownloadProgress']();
}

export function GetEmbeddingModelStatus() {
  return window['go']['main']['App']['GetEmbeddingModelStatus']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetIncognitoPrompt() {
  return window['go']['main']['App']['GetIncognitoPrompt']();
}

export function GetLlamaConfig() {
  return window['go']['main']['App']['GetLlamaConfig']();
}

export function GetLocalModelStatus() {
  return window['go']['main']['App']['GetLocalModelStatus']();
}

export function GetMemoryCount() {
  return window['go']['main']['App']['GetMemoryCount']();
}

export function GetModelFiles(arg1) {
  return window['go']['main']['App']['GetModelFiles'](arg1);
}

export function GetRemoteAccessStatus() {
  return window['go']['main']['App']['GetRemoteAccessStatus']();
}

export function GetSystemPrompt() {
  return window['go']['main']['App']['GetSystemPrompt']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function InstallLlamaServer() {
  return window['go']['main']['App']['InstallLlamaServer']();
}

export function ListChats() {
  return window['go']['main']['App']['ListChats']();
}

export function ListLocalModels() {
  return window['go']['main']['App']['ListLocalModels']();
}

export function ListMemoryFiles() {
  return window['go']['main']['App']['ListMemoryFiles']();
}

export function NewChat() {
  return window['go']['main']['App']['NewChat']();
}

export function RenameChat(arg1, arg2) {
  return window['go']['main']['App']['RenameChat'](arg1, arg2);
}

export function ResetSystemPrompt() {
  return window['go']['main']['App']['ResetSystemPrompt']();
}

export function SearchModels(arg1) {
  return window['go']['main']['App']['SearchModels'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SendMessageWithFile(arg1, arg2) {
  return window['go']['main']['App']['SendMessageWithFile'](arg1, arg2);
}

export function SendMessageWithImage(arg1, arg2) {
  return window['go']['main']['App']['SendMessageWithImage'](arg1, arg2);
}

export function SetEmbeddedAssets(arg1) {
  return window['go']['main']['App']['SetEmbeddedAssets'](arg1);
}

export function SetIncognitoPrompt(arg1) {
  return window['go']['main']['App']['SetIncognitoPrompt'](arg1);
}

export function SetLlamaBinaryPath(arg1) {
  return window['go']['main']['App']['SetLlamaBinaryPath'](arg1);
}

export function SetRemoteAccess(arg1, arg2) {
  return window['go']['main']['App']['SetRemoteAccess'](arg1, arg2);
}

export function SetSystemPrompt(arg1) {
  return window['go']['main']['App']['SetSystemPrompt'](arg1);
}

export function StartEmbeddingModel(arg1, arg2) {
  return window['go']['main']['App']['StartEmbeddingModel'](arg1, arg2);
}

export function StartLocalModel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartLocalModel'](arg1, arg2, arg3, arg4);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopEmbeddingModel() {
  return window['go']['main']['App']['StopEmbeddingModel']();
}

export function StopLocalModel() {
  return window['go']['main']['App']['StopLocalModel']();
}

export function StopRecordingAndTranscribe() {
  return window['go']['main']['App']['StopRecordingAndTranscribe']();
}

export function SwitchChat(arg1) {
  return window['go']['main']['App']['SwitchChat'](arg1);
}

export function ToggleIncognito(arg1) {
  return window['go']['main']['App']['ToggleIncognito'](arg1);
}

export function TranscribeAudio(arg1) {
  return window['go']['main']['App']['TranscribeAudio'](arg1);
}

export function UpdateIdentity(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateIdentity'](arg1, arg2, arg3);
}

export function WebCheckConnection() {
  return window['go']['main']['App']['WebCheckConnection']();
}

export function WebGetActiveMessages() {
  return window['go']['main']['App']['WebGetActiveMessages']();
}

export function WebListChats() {
  return window['go']['main']['App']['WebListChats']();
}
