// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {memory} from '../models';
import {llama} from '../models';
import {sessions} from '../models';
import {config} from '../models';
import {modelstore} from '../models';
import {embed} from '../models';

export function CancelDownload():Promise<void>;

export function CheckAuth():Promise<boolean>;

export function CheckConnection():Promise<main.ConnectionStatus>;

export function CheckEmbeddingHealth():Promise<Record<string, any>>;

export function CheckLlamaInstallation():Promise<boolean>;

export function CheckSyncAuth():Promise<boolean>;

export function ClearAllMemory():Promise<void>;

export function ClearHistory():Promise<void>;

export function DebugMemorySearch(arg1:string):Promise<Array<memory.MemoryResult>>;

export function DeleteChat(arg1:string):Promise<void>;

export function DeleteLocalModel(arg1:string):Promise<void>;

export function DeleteMemoryFile(arg1:string):Promise<void>;

export function DetectGPU():Promise<llama.GPUInfo>;

export function DownloadModel(arg1:string,arg2:string):Promise<void>;

export function GetActiveChatID():Promise<string>;

export function GetActiveMessages():Promise<Array<sessions.ChatMessage>>;

export function GetAvailableStyles():Promise<Array<string>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetDownloadProgress():Promise<modelstore.DownloadProgress>;

export function GetEmbeddingModelStatus():Promise<llama.ServerStatus>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetIncognitoPrompt():Promise<string>;

export function GetLlamaConfig():Promise<config.LlamaConfig>;

export function GetLocalModelStatus():Promise<llama.ServerStatus>;

export function GetMemoryCount():Promise<number>;

export function GetModelFiles(arg1:string):Promise<Array<modelstore.GGUFFile>>;

export function GetRemoteAccessStatus():Promise<main.RemoteAccessStatus>;

export function GetSyncAccount():Promise<main.SyncAccount>;

export function GetSyncSettings():Promise<config.SyncConfig>;

export function GetSystemPrompt():Promise<string>;

export function GetVersion():Promise<string>;

export function InstallLlamaServer():Promise<void>;

export function ListChats():Promise<Array<sessions.SessionInfo>>;

export function ListLocalModels():Promise<Array<modelstore.LocalModel>>;

export function ListMemoryFiles():Promise<Array<memory.GobFileInfo>>;

export function NewChat():Promise<string>;

export function PullSync():Promise<void>;

export function RenameChat(arg1:string,arg2:string):Promise<void>;

export function ResetSystemPrompt():Promise<void>;

export function SearchModels(arg1:string):Promise<Array<modelstore.HFModelResult>>;

export function SelectFile():Promise<string>;

export function SelectImage():Promise<string>;

export function SendMessage(arg1:string):Promise<string>;

export function SendMessageStream(arg1:string):Promise<void>;

export function SendMessageWithFile(arg1:string,arg2:string):Promise<string>;

export function SendMessageWithFileStream(arg1:string,arg2:string):Promise<void>;

export function SendMessageWithImage(arg1:string,arg2:string):Promise<string>;

export function SendMessageWithImageStream(arg1:string,arg2:string):Promise<void>;

export function SetEmbeddedAssets(arg1:embed.FS):Promise<void>;

export function SetIncognitoPrompt(arg1:string):Promise<void>;

export function SetLlamaBinaryPath(arg1:string):Promise<void>;

export function SetRemoteAccess(arg1:boolean,arg2:number):Promise<void>;

export function SetSystemPrompt(arg1:string):Promise<void>;

export function StartEmbeddingModel(arg1:string,arg2:number):Promise<void>;

export function StartLocalModel(arg1:string,arg2:number,arg3:number,arg4:number):Promise<void>;

export function StartRecording():Promise<void>;

export function StartSyncAuth():Promise<string>;

export function StopEmbeddingModel():Promise<void>;

export function StopLocalModel():Promise<void>;

export function StopRecordingAndTranscribe():Promise<string>;

export function SwitchChat(arg1:string):Promise<void>;

export function SyncNow():Promise<void>;

export function ToggleIncognito(arg1:boolean):Promise<void>;

export function TranscribeAudio(arg1:Array<number>):Promise<string>;

export function TriggerSync():Promise<void>;

export function UpdateIdentity(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateSyncSettings(arg1:boolean,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function WebCheckConnection():Promise<any>;

export function WebGetActiveMessages():Promise<any>;

export function WebListChats():Promise<any>;
