// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {sessions} from '../models';
import {config} from '../models';
import {memory} from '../models';

export function CheckConnection():Promise<main.ConnectionStatus>;

export function ClearAllMemory():Promise<void>;

export function ClearHistory():Promise<void>;

export function DeleteChat(arg1:string):Promise<void>;

export function DeleteMemoryFile(arg1:string):Promise<void>;

export function GetActiveChatID():Promise<string>;

export function GetActiveMessages():Promise<Array<sessions.ChatMessage>>;

export function GetAvailableStyles():Promise<Array<string>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetIncognitoPrompt():Promise<string>;

export function GetMemoryCount():Promise<number>;

export function GetSystemPrompt():Promise<string>;

export function ListChats():Promise<Array<sessions.SessionInfo>>;

export function ListMemoryFiles():Promise<Array<memory.GobFileInfo>>;

export function NewChat():Promise<string>;

export function RenameChat(arg1:string,arg2:string):Promise<void>;

export function ResetSystemPrompt():Promise<void>;

export function SelectFile():Promise<string>;

export function SelectImage():Promise<string>;

export function SendMessage(arg1:string):Promise<string>;

export function SendMessageWithFile(arg1:string,arg2:string):Promise<string>;

export function SendMessageWithImage(arg1:string,arg2:string):Promise<string>;

export function SetIncognitoPrompt(arg1:string):Promise<void>;

export function SetSystemPrompt(arg1:string):Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecordingAndTranscribe():Promise<string>;

export function SwitchChat(arg1:string):Promise<void>;

export function ToggleIncognito(arg1:boolean):Promise<void>;

export function UpdateIdentity(arg1:string,arg2:string,arg3:string):Promise<void>;
