// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function ClearAllMemory() {
  return window['go']['main']['App']['ClearAllMemory']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteChat(arg1) {
  return window['go']['main']['App']['DeleteChat'](arg1);
}

export function DeleteMemoryFile(arg1) {
  return window['go']['main']['App']['DeleteMemoryFile'](arg1);
}

export function GetActiveChatID() {
  return window['go']['main']['App']['GetActiveChatID']();
}

export function GetActiveMessages() {
  return window['go']['main']['App']['GetActiveMessages']();
}

export function GetAvailableStyles() {
  return window['go']['main']['App']['GetAvailableStyles']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetIncognitoPrompt() {
  return window['go']['main']['App']['GetIncognitoPrompt']();
}

export function GetMemoryCount() {
  return window['go']['main']['App']['GetMemoryCount']();
}

export function GetSystemPrompt() {
  return window['go']['main']['App']['GetSystemPrompt']();
}

export function ListChats() {
  return window['go']['main']['App']['ListChats']();
}

export function ListMemoryFiles() {
  return window['go']['main']['App']['ListMemoryFiles']();
}

export function NewChat() {
  return window['go']['main']['App']['NewChat']();
}

export function RenameChat(arg1, arg2) {
  return window['go']['main']['App']['RenameChat'](arg1, arg2);
}

export function ResetSystemPrompt() {
  return window['go']['main']['App']['ResetSystemPrompt']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SendMessageWithFile(arg1, arg2) {
  return window['go']['main']['App']['SendMessageWithFile'](arg1, arg2);
}

export function SendMessageWithImage(arg1, arg2) {
  return window['go']['main']['App']['SendMessageWithImage'](arg1, arg2);
}

export function SetIncognitoPrompt(arg1) {
  return window['go']['main']['App']['SetIncognitoPrompt'](arg1);
}

export function SetSystemPrompt(arg1) {
  return window['go']['main']['App']['SetSystemPrompt'](arg1);
}

export function SwitchChat(arg1) {
  return window['go']['main']['App']['SwitchChat'](arg1);
}

export function ToggleIncognito(arg1) {
  return window['go']['main']['App']['ToggleIncognito'](arg1);
}

export function UpdateIdentity(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateIdentity'](arg1, arg2, arg3);
}
